In [1]:
import numpy as np

In [39]:
def weighted_centroid(points, weights):
    res = points
    while len(res) > 1:
        new_res = []
        new_weights = []
        for i in range(0,len(res),2):
            p1 = res[i]
            p2 = res[i+1]
            w1 = weights[i]
            w2 = weights[i+1]
            
            vector = np.array(p2) - np.array(p1)
            #length = np.linalg.norm(vector)
            
            percentage = w1 / (w1 + w2)
            p = p1 + percentage*vector

            new_res.append(p)
            new_weights.append(w1 + w2)
        res = new_res
        weights = new_weights
    return res

In [40]:
p1 = (-1, 0)
p2 = (1, 0)

vector = np.array(p2) - np.array(p1)

vector

array([2, 0])

In [44]:
p4 = weighted_centroid([p1, p2], [0.4, 0.4])
p4

[(-1, 0), (1, 0)]
0.5
[0. 0.]


[array([0., 0.])]

In [32]:
# length of vector
length = np.linalg.norm(vector)
length

2.0

In [33]:
#normalize the vecotor
vector = vector / length
vector

array([1., 0.])

In [34]:
#get point at 60%
p = p1 + length*0.6*vector

p

array([0.2, 0. ])